# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name for the category. Limited to 64 characters.', max_length=64)),
                ('slug', models.SlugField(help_text='Short name for use in urls.', max_length=64, unique=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Connect to another node, or null (cconnection to self forbidden)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', related_query_name='children', to='taxonomy.TermNode')),
            ],
        ),
        migrations.RemoveField(
            model_name='node',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
    ]
