# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_auto_20170810_1058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TermNode',
            new_name='Term',
        ),
    ]
