# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_auto_20170810_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Priority for display in some templates. Higher priority orders first. 0 to 32767.'),
        ),
    ]
