# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0004_term_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Connect to another node, or null (cconnection to self forbidden)', null=True, on_delete=django.db.models.deletion.CASCADE, to='taxonomy.Term'),
        ),
    ]
