# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0006_auto_20170816_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyTerm',
            fields=[
                ('term', models.OneToOneField(help_text='A Term associated with a Taxonomy.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='taxonomy.Term')),
                ('taxonomy', models.ForeignKey(help_text='A Taxonomy associated with a Term.', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.Taxonomy')),
            ],
        ),
        migrations.AlterField(
            model_name='termnode',
            name='node',
            field=models.IntegerField(db_index=True, help_text='Id of an element associated with a Term.'),
        ),
        migrations.AlterField(
            model_name='termnode',
            name='term',
            field=models.ForeignKey(help_text='A Term associated with an element.', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.Term'),
        ),
    ]
