# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0010_auto_20170904_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxonomynodetype',
            name='taxonomy',
        ),
        migrations.DeleteModel(
            name='TaxonomyNodetype',
        ),
    ]
