# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0012_auto_20170904_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='termtaxonomy',
            old_name='taxonomy',
            new_name='tree',
        ),
    ]
