# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0013_auto_20170904_2126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TermTaxonomy',
            new_name='TermTree',
        ),
    ]
