# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0014_auto_20170904_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Description of the category. Limited to 255 characters.', max_length=255),
        ),
        migrations.AddField(
            model_name='tree',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Overall description of the collection of categories. Limited to 255 characters.', max_length=255),
        ),
        migrations.AlterField(
            model_name='term',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, default=0, help_text='Priority for display in some templates. Lower value orders first. 0 to 32767.'),
        ),
        migrations.AlterField(
            model_name='termnode',
            name='node',
            field=models.IntegerField(db_index=True, help_text='An element associated with a Term.'),
        ),
        migrations.AlterField(
            model_name='termtree',
            name='term',
            field=models.OneToOneField(help_text='A Term associated with a Tree.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='taxonomy.Term'),
        ),
        migrations.AlterField(
            model_name='termtree',
            name='tree',
            field=models.ForeignKey(help_text='A Tree associated with a Term.', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.Tree'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, default=0, help_text='Priority for display in some templates. Lower value orders first. 0 to 32767.'),
        ),
    ]
