# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0015_auto_20170905_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termparent',
            name='parent',
            field=models.IntegerField(blank=True, db_index=True, help_text='Term parent for another term, or null for root (connection to self forbidden)', null=True),
        ),
    ]
