# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0016_auto_20170905_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termparent',
            name='parent',
            field=models.IntegerField(db_index=True, default=-1, help_text='Term parent for another term, or null for root (connection to self forbidden)'),
            preserve_default=False,
        ),
    ]
