# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0018_term_tree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termtree',
            name='term',
        ),
        migrations.RemoveField(
            model_name='termtree',
            name='tree',
        ),
        migrations.DeleteModel(
            name='TermTree',
        ),
    ]
