# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0020_auto_20170924_0549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='termnode',
            old_name='node',
            new_name='elem',
        ),
    ]
