# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0021_auto_20170924_0550'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TermNode',
            new_name='TermElem',
        ),
        migrations.AlterField(
            model_name='tree',
            name='is_unique',
            field=models.BooleanField(default=False, help_text='Nunber of parents allowed for a element in the taxonomy (True = one only, False = many).'),
        ),
    ]
