# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0022_auto_20170924_0559'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TermElem',
            new_name='Element',
        ),
    ]
