# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0023_auto_20170924_0613'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tree',
            new_name='Base',
        ),
        migrations.DeleteModel(
            name='TreeTerm',
        ),
        migrations.AlterField(
            model_name='element',
            name='tree',
            field=models.IntegerField(db_index=True, help_text='A Base associated with an element.'),
        ),
        migrations.AlterField(
            model_name='term',
            name='tree',
            field=models.IntegerField(db_index=True, help_text='A Base associated with this Term.'),
        ),
    ]
