# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0025_baseterm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseterm',
            name='id',
        ),
        migrations.RemoveField(
            model_name='element',
            name='tree',
        ),
        migrations.RemoveField(
            model_name='term',
            name='tree',
        ),
        migrations.AlterField(
            model_name='baseterm',
            name='term',
            field=models.IntegerField(db_index=True, help_text='Term associated with a Base', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='termparent',
            name='parent',
            field=models.IntegerField(db_index=True, help_text='Term parenting another term.'),
        ),
        migrations.AlterField(
            model_name='termparent',
            name='term',
            field=models.IntegerField(db_index=True, help_text='Term parented by another term.'),
        ),
    ]
