# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0026_auto_20170924_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='title',
            field=models.CharField(db_index=True, help_text='Name for a tree of categories. Limited to 255 characters.', max_length=255, unique=True),
        ),
    ]
